### ISSUE TITLE
Add support for lv95

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/service-alti#23]
@procrastinatio if you want to contribute, you can take this part.

To coordinate with @ltclm , I don't think we have enough disk space on our EBS at the moment.
Unless, you want to try the "on the fly approach".

**Comment by ltclm** [comment]
no there is not enough diskspace  at the moment
```
/dev/xvdp    148G    103G   38G   74% /var/local/profile
```
@danduk82 has to mount a bigger disk first. then we will have to duplicate and rsync the existing data (LV03->LV95 shift)

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/service-alti/pull/26

**Comment by rebert** [comment]
I will just have to copy the data @danduk82 added space - I will have to do it

**Comment by procrastinatio** [comment]
Done.
