### ISSUE TITLE
Profile doesn't support 'multipart/form-data'

### ISSUE THREAD

**Issue by oterral** [geoadmin/service-alti#33]
When we sent a POST request to profile.json with data in the body as 'multipart/form-data', it works if the header Content-Type is  set to undefined but  doesn't works if the Content-Type is set to 'multipart/form-data'.

**Comment by pakb** [comment]
has been (partially or totally) covered by https://github.com/geoadmin/service-alti/pull/47
It is now possible to transmit the geom trough a POST body and others params through URL params. This enable us to send bigger geometries (like the ones we want to test for wanderweg with more than 2000 points, too big to fit in the 2048 char limit of URLs)
