### ISSUE TITLE
Keep only COMB

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/service-alti#55]
See mail thread "Height-Service : 2m --> 0.5m && neue hillshade"11.2.2020 and https://github.com/geoadmin/mf-geoadmin3/projects/2#card-21739280

Task
keep only "comb" option of service

Action
- [x]  Who are the DTM" users? -> @ltclm 
- [x]  Inform Schweizmobil and DTM2 users that we will only operate the comb service (per next deploy) -> @davidoesch 
- [x] Adaptation of the doc https://api3.geo.admin.ch/services/sdiservices.html#height and https://api3.geo.admin.ch/services/sdiservices.html#profile and mention in release notes -> @ltclm
https://github.com/geoadmin/mf-chsdi3/pull/3392
- [x] Adaption of service-alti -> @pakb 

Result:
next deploy only comb availbale and services are less complex

**Comment by ltclm** [comment]
DTM users (IP/referer) sent by mail, since this is a public repo.

**Comment by ltclm** [comment]
@boecklic @davidoesch 

Do you want that we 
* ignore the content of the parameter ``elevation_model``
* keep only ``COMP`` as valid elevation_model

**Comment by ltclm** [comment]
@pakb 
With the latest update of profile data we have to update service-alti for the next deploy.
the new datasource of profile data on efs is:
```
/var/local/geodata/bund/swisstopo/swissalti3d/kombo_2m_regio
/var/local/geodata/bund/swisstopo/swissalti3d/kombo_2m_regio_lv95
```
This dataset will be published as elevation_model ``COMB``, the other elevation models ``DTM25, DTM2`` are not supported anymore and can be removed from the valid values.
can you please modifiy the service and prepare a pr for the next deploy
Thank you

**Comment by procrastinatio** [comment]
@ltclm If only one model, no need to keep it as `elevation_model` (but describe it in the doku)

**Comment by procrastinatio** [comment]
@ltclm `mf-chsdi3` and `service-alti` may be deployed independently.

**Comment by ltkum** [comment]
This has been merged already. I'm closing the issue.

**Comment by davidoesch** [comment]
hi @ltkum don't close issue if there are open action points in the description.
mine was still open: confirmation by chmobil was received today
@pakb can you confitm the open point above?

**Comment by ltclm** [comment]
please adapt the tests 
scripts/generate-test-data.sh

**Comment by ltclm** [comment]
@pakb im not able to re-open this issue, could you please adapt the tests. Thank you!

**Comment by davidoesch** [comment]
Hi all

As informed by CHMOBIL today

> We have tested the new Service-alti and as @eleu  found out, it does not behave exactly as the old service. This is a blocking issue for us and we ask you not to set it live without solved this issue the 18.3.2020, otherwise we would get a lot of negative customer feedbacks.

> We stand by for testing again if you will deliver us a corrected service: time is very short for testing again, but we would try before 18.3.20.

-> THEREFORE on hold
@eleu  can ypou please elaborate the differences?

**Comment by ltclm** [comment]
why cant we ping mario keusen here??

**Comment by pakb** [comment]
because he is not part of the group chtopo_igeb which is weird, I've added chtopo_dashboard as reader of the repo, you should be able to ping him now

**Comment by ltclm** [comment]
@mariokeusen we have issues with the new height data. it was planned to update the height service together with the new hillshade version, do you want us to take the hillshade out of the deploy next week? i think this issue will take longer to be solved...

**Comment by mariokeusen** [comment]
Hillshade can be published as planned.

**Comment by eleu** [comment]
> @eleu can ypou please elaborate the differences?

Sure, here you go:

When I am drawing outside of Switzerland (f.e. the start point in the region between Besançon and Switzerland, and the end point in Switzerland), the old service returned a 400 error code:
```
{,…}
message: "The server could not comply with the request since it is either malformed or otherwise incorrect.↵↵↵No 'sr' given and cannot be guessed from 'geom'↵↵"
code: "400 Bad Request"
title: "Bad Request"
```

We are catching and treating this error on SchweizMobil side.

But now, with the new service, it seems to return a 500 error message:
```
{,…}
message: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">↵<html><head>↵<title>500 Internal Server Error</title>↵</head><body>↵<h1>Internal Server Error</h1>↵<p>The server encountered an internal error or↵misconfiguration and was unable to complete↵your request.</p>↵<p>Please contact the server administrator at ↵ [no address given] to inform them of the time this error occurred,↵ and the actions you performed just before this error.</p>↵<p>More information about this error may be available↵in the server error log.</p>↵</body></html>↵"
status: 500

```
Can you change it back to the 400 Bad Request error?

**Comment by davidoesch** [comment]
and chmnil feedback 
"and explained that it is probably a bit of a corner case that we detected. (still, corner cases might mean some user feedback because there are many and many creative users...)
CHMOBIL would be OK if it would be fixed in a second step, in max 1 months after the deploy, if it is not possible to fix for the 18th of March
"

proposal:
-  we fix this NOW  once and for all

upvotes or downvotes @pakb @boecklic

**Comment by ltclm** [comment]
the new heigth / profile service perimeter looks like this:
https://s.geo.admin.ch/87f9621dc8
Just in case you want to tests some corner cases.
For the given example there should be no error at all because we have data in this region.

**Comment by eleu** [comment]
thanks @ltclm, good to know, but with that info I doubt that the data is available according to the grid.

A better test case:
This in **prod** is working fine:
https://s.geo.admin.ch/87f9786ab1
`curl 'https://api3.geo.admin.ch/rest/services/profile.json' -H 'authority: api3.geo.admin.ch' -H 'pragma: no-cache' -H 'cache-control: no-cache' -H 'accept: application/json, text/plain, */*' -H 'sec-fetch-dest: empty' -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36' -H 'content-type: application/x-www-form-urlencoded' -H 'origin: https://map.geo.admin.ch' -H 'sec-fetch-site: same-site' -H 'sec-fetch-mode: cors' -H 'referer: https://map.geo.admin.ch/' -H 'accept-language: de-CH,de;q=0.9,en;q=0.8,it;q=0.7,fr-CH;q=0.6,fr;q=0.5,it-CH;q=0.4,en-US;q=0.3' --data 'geom=%7B%22type%22%3A%22LineString%22%2C%22coordinates%22%3A%5B%5B2497000.0%2C1226750.0%5D%2C%5B2544000.0%2C1208750.0%5D%5D%7D&elevation_models=COMB&offset=1' --compressed`


But when I just change the base address to the new service on **integration**, it returns a error 500:

`curl 'https://service-alti.int.bgdi.ch/rest/services/profile.json' -H 'authority: api3.geo.admin.ch' -H 'pragma: no-cache' -H 'cache-control: no-cache' -H 'accept: application/json, text/plain, */*' -H 'sec-fetch-dest: empty' -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36' -H 'content-type: application/x-www-form-urlencoded' -H 'origin: https://map.geo.admin.ch' -H 'sec-fetch-site: same-site' -H 'sec-fetch-mode: cors' -H 'referer: https://map.geo.admin.ch/' -H 'accept-language: de-CH,de;q=0.9,en;q=0.8,it;q=0.7,fr-CH;q=0.6,fr;q=0.5,it-CH;q=0.4,en-US;q=0.3' --data 'geom=%7B%22type%22%3A%22LineString%22%2C%22coordinates%22%3A%5B%5B2497000.0%2C1226750.0%5D%2C%5B2544000.0%2C1208750.0%5D%5D%7D&elevation_models=COMB&offset=1' --compressed`

**Comment by ltclm** [comment]
the data behind service-alti.int.bgdi.ch has not been updated correctly.
Im am currently syncing the data from EFS to the local SSD storage on the two int instances. Once finished, the service should work correctly.

**Comment by ltclm** [comment]
hello @eleu 
we have fixed the test link (service-alti.int.bgdi.ch), you can now test the new version of the service with the new data.
sorry for the inconvenience.

**Comment by ltclm** [comment]
@pakb we still have have the deprecated elevation models in the service response: 
``{"DTM2":1070.7,"COMB":1070.7,"DTM25":1070.7}``

this should be replaced with
``{"COMB":1070.7}``

**Comment by pakb** [comment]
No this is on purpose to be retro compatible. When someone will ask an old elevation model, he will expect it to be present in the response. The service returns the value of the new model for every known old elevation model.

**Comment by pakb** [comment]
So we should be all good, here's a request that goes out of bound : https://mf-chsdi3.int.bgdi.ch/shorten/87fe11038f it responds with a HTTP 400 (the error is not very accurate as it's not a SR problem, anyway...)
and here is a request that is around Besançon (in bounds) and responds correctly : https://mf-chsdi3.int.bgdi.ch/shorten/87fe104e94

**Comment by eleu** [comment]
@ltclm and @pakb OK great, it's already better especially with more data around Switzerland.

I still found that we get 500 error at SchweizMobil sadly, if we are very much outside. The reason is that, if you send the sr=2056, it will still return a 500 instead of 400 error.

Can you fix this?

Sample request:
`curl 'https://service-alti.int.bgdi.ch/rest/services/profile.json' -H 'origin: https://map.geo.admin.ch' --data 'geom=%7B%22type%22%3A%22LineString%22%2C%22coordinates%22%3A%5B%5B2362000.0%2C1159250.0%5D%2C%5B2433000.0%2C1050250.0%5D%5D%7D&elevation_models=COMB&offset=1&sr=2056' --compressed`

**Comment by pakb** [comment]
I'll try to check if given coordinates are in bound according to SR, if not it should return a HTTP 400 with a clear message.

**Comment by pakb** [comment]
@eleu You can test once again, it should now respond with HTTP 400 if you have provided out of bounds coordinates (when specifying sr=2056)

**Comment by eleu** [comment]
Ok thanks a lot @pakb 

I just realized that currently on prod, it returns [] if its outside of the bounds...

f.e. `curl 'https://api3.geo.admin.ch/rest/services/profile.json' -H 'origin: https://map.geo.admin.ch' --data 'geom=%7B%22type%22%3A%22LineString%22%2C%22coordinates%22%3A%5B%5B2362000.0%2C1159250.0%5D%2C%5B2433000.0%2C1050250.0%5D%5D%7D&elevation_models=COMB&offset=1&sr=2056' --compressed`

Sorry this was really my bad, I did not provide the right testing URL's (it was hard to reconstruct, as we are doing the request in a not so obvious way). So it might be better to return [] instead of error 400 in this case... I am really sorry about that!

Also I discussed with SchweizMobil, for them the larger available data is really great and it is OK for them like that, so the "out of bound" error is not so important / urgent.

**Comment by pakb** [comment]
So I've deployed on INT a new version that should respond as the PROD does. It will return an empty profile if SR is given and coordinates are out of bounds.

**Comment by eleu** [comment]
@pakb  Oh great, I just tested, it looks perfect! (I only tested this case, not much more though).

**Comment by pakb** [comment]
has been deployed on prod
